# Generated by Django 3.1.5 on 2021-03-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210303_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=220),
        ),
    ]
