# Generated by Django 3.1.5 on 2021-03-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dicription',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
