# Generated by Django 3.1.5 on 2021-03-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210313_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dicription',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
