# Generated by Django 3.1.5 on 2021-04-28 11:05

from django.db import migrations, models
import product.storages


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210426_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, null=True, storage=product.storages.ProtectedStorage, upload_to='product/'),
        ),
    ]
