# Generated by Django 3.1.5 on 2021-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_inventory_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_of_order',
            field=models.IntegerField(default=1),
        ),
    ]
